import Testing
import Foundation
@testable import ModelForgeKit

@Suite("Emitters")
struct EmitterTests {

    private func generate(_ files: [SourceFile],
                          configuration: ProjectConfiguration = .default) -> CompilePipeline.Output {
        CompilePipeline.run(files: files, configuration: configuration)
    }

    private func source(_ text: String, named name: String = "test.model") -> [SourceFile] {
        [SourceFile(id: SourceFileID(0), name: name, text: text)]
    }

    // MARK: Fixtures

    @Test("generates the end-to-end example across two files")
    func endToEndFixture() {
        let output = generate(Snapshot.project("EndToEnd"))
        #expect(output.result.diagnostics.isEmpty)

        for file in output.generated.files {
            Snapshot.assert(file.contents, matches: "Generation/EndToEnd/expected/\(file.name)")
        }
        // One Swift and one Kotlin file per source file — the preview always matches the
        // file being edited.
        #expect(output.generated.files.map(\.name).sorted()
                == ["Actions.kt", "Actions.swift", "ModelForgeSupport.kt",
                    "ModelForgeSupport.swift", "User.kt", "User.swift"])
    }

    // MARK: File naming

    @Test("output file names come from the source file's name")
    func fileNaming() {
        let output = generate([
            SourceFile(id: SourceFileID(0), name: "user_profile.model", text: "model A { id: UUID }")
        ])
        #expect(output.generated.files.filter { $0.sourceFile != nil }.map(\.name).sorted()
                == ["UserProfile.kt", "UserProfile.swift"])
    }

    @Test("an empty source file still generates a header-only file")
    func emptyFileStillGenerates() {
        let output = generate(source(""))
        // Two per source file, plus the two shared support files.
        #expect(output.generated.files.count == 4)
        for file in output.generated.files {
            #expect(file.contents.contains("Generated by ModelForge"))
        }
    }

    // MARK: Swift specifics

    @Test("a model with no defaults keeps Codable synthesis")
    func simpleModelUsesSynthesis() {
        let output = generate(source("model A { id: UUID\n name: String }"))
        let swift = output.generated.files(for: .swift)[0].contents
        #expect(!swift.contains("init(from decoder"))
        #expect(!swift.contains("CodingKeys"))
        #expect(swift.contains("struct A: Codable, Equatable, Sendable {"))
    }

    @Test("a default becomes decodeIfPresent, so the key may be absent")
    func defaultsDecodeWhenAbsent() {
        let output = generate(source("model A { archived: Bool = false }"))
        let swift = output.generated.files(for: .swift)[0].contents
        #expect(swift.contains("self.archived = try container.decodeIfPresent(Bool.self, forKey: .archived) ?? false"))
    }

    @Test("an optional without a default still requires its key")
    func optionalWithoutDefaultRequiresKey() {
        let output = generate(source("model A { email: String? }"))
        let swift = output.generated.files(for: .swift)[0].contents
        #expect(swift.contains("try container.decode((String?).self, forKey: .email)"))
    }

    @Test("a nil optional is encoded as null rather than dropped")
    func nilEncodesAsNull() {
        let output = generate(source("model A { email: String? }"))
        let swift = output.generated.files(for: .swift)[0].contents
        // Synthesis would use encodeIfPresent and omit the key; kotlinx writes the null,
        // so Swift has to as well or the two platforms disagree on the wire.
        #expect(swift.contains("func encode(to encoder: any Encoder) throws"))
        #expect(swift.contains("try container.encode(self.email, forKey: .email)"))
    }

    @Test("public access level makes the members public")
    func publicAccessLevel() {
        var configuration = ProjectConfiguration.default
        configuration.swift.accessLevel = .public
        let output = generate(source("model A { id: UUID }"), configuration: configuration)
        let swift = output.generated.files(for: .swift)[0].contents
        #expect(swift.contains("public struct A"))
        #expect(swift.contains("public let id: UUID"))
        #expect(swift.contains("public init(id: UUID)"))
    }

    @Test("conformances follow the configuration")
    func configurableConformances() {
        var configuration = ProjectConfiguration.default
        configuration.swift.hashable = true
        configuration.swift.sendable = false
        let output = generate(source("model A { id: UUID }"), configuration: configuration)
        #expect(output.generated.files(for: .swift)[0].contents.contains("struct A: Codable, Hashable {"))
    }

    @Test("a recursive union becomes indirect in Swift")
    func recursiveUnionIsIndirect() {
        let output = generate(source("""
        union Expr { negated(Negation) }
        model Negation { inner: Expr }
        """))
        #expect(output.generated.files(for: .swift)[0].contents.contains("indirect enum Expr"))
    }

    @Test("keyword member names are escaped on both platforms")
    func keywordsAreEscaped() {
        let output = generate(source("model A { `class`: String\n `object`: String }"
            .replacingOccurrences(of: "`", with: "")))
        #expect(output.generated.files(for: .swift)[0].contents.contains("let `class`: String"))
        #expect(output.generated.files(for: .kotlin)[0].contents.contains("val `object`: String"))
    }

    // MARK: Kotlin specifics

    @Test("file annotations precede the package declaration")
    func fileAnnotationsComeFirst() {
        let output = generate(source("model A { id: UUID }"))
        let kotlin = output.generated.files(for: .kotlin)[0].contents
        let optIn = kotlin.range(of: "@file:OptIn")
        let package = kotlin.range(of: "package ")
        #expect(optIn != nil && package != nil)
        #expect(optIn!.lowerBound < package!.lowerBound)
    }

    @Test("only the scalars actually used are imported")
    func importsAreMinimal() {
        let output = generate(source("model A { name: String }"))
        let kotlin = output.generated.files(for: .kotlin)[0].contents
        #expect(!kotlin.contains("import kotlin.uuid.Uuid"))
        #expect(!kotlin.contains("@file:OptIn"))
        #expect(kotlin.contains("import kotlinx.serialization.Serializable"))
    }

    @Test("enum constants are SCREAMING_SNAKE but the wire value is the DSL spelling")
    func enumConstantsAndWireValues() {
        let output = generate(source("enum Method { applePay\n httpGet }"))
        let kotlin = output.generated.files(for: .kotlin)[0].contents
        #expect(kotlin.contains("@SerialName(\"applePay\")"))
        #expect(kotlin.contains("APPLE_PAY,"))
        #expect(kotlin.contains("HTTP_GET,"))
    }

    @Test("union payloads implement the sealed interface, even across files")
    func sealedInterfaceAcrossFiles() {
        let output = generate([
            SourceFile(id: SourceFileID(0), name: "union.model",
                       text: "union Payment { card(Card) }"),
            SourceFile(id: SourceFileID(1), name: "card.model",
                       text: "model Card { number: String }")
        ])
        let unionFile = output.generated.file(for: SourceFileID(0), language: .kotlin)!.contents
        let cardFile = output.generated.file(for: SourceFileID(1), language: .kotlin)!.contents
        #expect(unionFile.contains("sealed interface Payment"))
        #expect(cardFile.contains("@SerialName(\"card\")"))
        #expect(cardFile.contains(") : Payment"))
    }

    @Test("Kotlin numeric defaults get the literal form Kotlin requires")
    func kotlinNumericLiterals() {
        let output = generate(source("""
        model A {
            f: Float = 1
            d: Double = 2
            g: Float = 1.5
            m: Decimal = 1.5
            i: Int64 = 7
        }
        """))
        let kotlin = output.generated.files(for: .kotlin)[0].contents
        // Kotlin will not widen an integer literal to a floating-point type the way Swift does.
        #expect(kotlin.contains("val f: Float = 1.0f"))
        #expect(kotlin.contains("val d: Double = 2.0"))
        #expect(kotlin.contains("val g: Float = 1.5f"))
        #expect(kotlin.contains("val m: BigDecimal = BigDecimal(\"1.5\")"))
        #expect(kotlin.contains("val i: Long = 7"))
    }

    @Test("defaulted properties are forced onto the wire")
    func kotlinEncodesDefaults() {
        let output = generate(source("model A { retries: Int32 = 0 }"))
        let kotlin = output.generated.files(for: .kotlin)[0].contents
        // kotlinx omits a value equal to its default; Swift does not, so it is forced.
        #expect(kotlin.contains("@EncodeDefault"))
    }

    // MARK: Determinism

    @Test("generating twice produces identical bytes")
    func generationIsDeterministic() {
        let files = Snapshot.project("EndToEnd")
        let first = generate(files).generated.files.map(\.contents)
        let second = generate(files).generated.files.map(\.contents)
        #expect(first == second)
    }

    @Test("output contains nothing that varies between runs")
    func noTimestampsInOutput() {
        let output = generate(Snapshot.project("EndToEnd"))
        for file in output.generated.files {
            #expect(!file.contents.contains("\(Calendar.current.component(.year, from: Date()))"))
        }
    }

    @Test("an unresolved type flows through verbatim so previews keep rendering")
    func unresolvedTypesStillRender() {
        let output = generate(source("model A { manager: Usre }"))
        #expect(output.result.hasErrors)
        #expect(output.generated.files(for: .swift)[0].contents.contains("let manager: Usre"))
        #expect(output.generated.files(for: .kotlin)[0].contents.contains("val manager: Usre"))
    }

    // MARK: Cross-platform wire formats

    // Each of these came from encoding the same value on both platforms and comparing the
    // bytes. Before the support file existed, Swift wrote a 2001-epoch number for an
    // Instant while Kotlin wrote an ISO-8601 string — Swift could not decode Kotlin's
    // payload at all — and the Kotlin generated for Date and Decimal did not compile.

    @Test("generates every scalar type")
    func allScalarsFixture() {
        var configuration = ProjectConfiguration.default
        configuration.kotlin.package = "com.example.models"
        let output = generate(Snapshot.project("AllScalars"), configuration: configuration)
        #expect(output.result.diagnostics.isEmpty)
        for file in output.generated.files {
            Snapshot.assert(file.contents, matches: "Generation/AllScalars/expected/\(file.name)")
        }
    }

    @Test("a support file is generated for each language")
    func supportFilesAreGenerated() {
        let output = generate(source("model A { at: Instant }"))
        let swift = output.generated.files.first { $0.name == "ModelForgeSupport.swift" }
        let kotlin = output.generated.files.first { $0.name == "ModelForgeSupport.kt" }
        #expect(swift != nil)
        #expect(kotlin != nil)
        // It belongs to the project rather than to any one source file.
        #expect(swift?.sourceFile == nil)
        #expect(kotlin?.contents.contains("package com.example.models") == true)
    }

    @Test("Instant is coded as ISO-8601 on both platforms")
    func instantUsesISO8601() {
        let output = generate(source("model A { at: Instant }"))
        let swift = modelFile(output, .swift)
        // Stock Codable would write a number of seconds from 2001, which Kotlin cannot read.
        #expect(swift.contains("ModelForgeInstant.self, forKey: .at"))
        #expect(swift.contains("try container.encode(ModelForgeInstant(self.at), forKey: .at)"))
        #expect(modelFile(output, .kotlin).contains("@file:UseSerializers(ModelForgeInstantSerializer::class)"))
    }

    @Test("Date becomes a generated type rather than a dependency")
    func dateAvoidsKotlinxDatetime() {
        let output = generate(source("model A { on: Date }"))
        #expect(modelFile(output, .swift).contains("let on: ModelForgeDate"))
        #expect(modelFile(output, .kotlin).contains("val on: ModelForgeDate"))
        // kotlinx.datetime would be a dependency the project may not have.
        #expect(!modelFile(output, .kotlin).contains("kotlinx.datetime"))
    }

    @Test("Decimal gets a serializer, since kotlinx has none for BigDecimal")
    func decimalGetsASerializer() {
        let output = generate(source("model A { amount: Decimal }"))
        #expect(modelFile(output, .kotlin).contains("ModelForgeDecimalSerializer::class"))
    }

    @Test("wire conversion reaches inside containers")
    func wireConversionNests() {
        let output = generate(source("model A { times: [Instant]\n byName: Map<String, Instant>\n maybe: Instant? }"))
        let swift = modelFile(output, .swift)
        #expect(swift.contains("[ModelForgeInstant].self, forKey: .times"))
        #expect(swift.contains(".map { $0.value }"))
        #expect(swift.contains(".mapValues { $0.value }"))
        #expect(swift.contains("(ModelForgeInstant?).self, forKey: .maybe"))
    }

    @Test("a model using none of them keeps synthesized Codable")
    func ordinaryModelsAreUntouched() {
        let output = generate(source("model A { id: UUID\n name: String }"))
        let swift = modelFile(output, .swift)
        #expect(!swift.contains("init(from decoder"))
        // The header names ModelForge; nothing else should have to.
        #expect(!swift.contains("ModelForgeInstant"))
        #expect(!swift.contains("ModelForgeDate"))
        #expect(!modelFile(output, .kotlin).contains("UseSerializers"))
    }

    /// The generated model file for a language, excluding the shared support file.
    private func modelFile(_ output: CompilePipeline.Output, _ language: Language) -> String {
        output.generated.files.first { $0.language == language && $0.sourceFile != nil }?.contents ?? ""
    }
}
