// Generated by ModelForge. Do not edit manually.

import Foundation

struct AllScalars: Codable, Equatable, Sendable {
    let s: String
    let b: Bool
    let i32: Int32
    let i64: Int64
    let f: Float
    let d: Double
    let dec: Decimal
    let uuid: UUID
    let url: URL
    let date: ModelForgeDate
    let instant: Date
    let duration: Duration

    private enum CodingKeys: String, CodingKey {
        case s
        case b
        case i32
        case i64
        case f
        case d
        case dec
        case uuid
        case url
        case date
        case instant
        case duration
    }

    init(
        s: String,
        b: Bool,
        i32: Int32,
        i64: Int64,
        f: Float,
        d: Double,
        dec: Decimal,
        uuid: UUID,
        url: URL,
        date: ModelForgeDate,
        instant: Date,
        duration: Duration
    ) {
        self.s = s
        self.b = b
        self.i32 = i32
        self.i64 = i64
        self.f = f
        self.d = d
        self.dec = dec
        self.uuid = uuid
        self.url = url
        self.date = date
        self.instant = instant
        self.duration = duration
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.s = try container.decode(String.self, forKey: .s)
        self.b = try container.decode(Bool.self, forKey: .b)
        self.i32 = try container.decode(Int32.self, forKey: .i32)
        self.i64 = try container.decode(Int64.self, forKey: .i64)
        self.f = try container.decode(Float.self, forKey: .f)
        self.d = try container.decode(Double.self, forKey: .d)
        self.dec = try container.decode(Decimal.self, forKey: .dec)
        self.uuid = try container.decode(UUID.self, forKey: .uuid)
        self.url = try container.decode(URL.self, forKey: .url)
        self.date = try container.decode(ModelForgeDate.self, forKey: .date)
        let instant = try container.decode(ModelForgeInstant.self, forKey: .instant)
        self.instant = instant.value
        let duration = try container.decode(ModelForgeDuration.self, forKey: .duration)
        self.duration = duration.value
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.s, forKey: .s)
        try container.encode(self.b, forKey: .b)
        try container.encode(self.i32, forKey: .i32)
        try container.encode(self.i64, forKey: .i64)
        try container.encode(self.f, forKey: .f)
        try container.encode(self.d, forKey: .d)
        try container.encode(self.dec, forKey: .dec)
        try container.encode(self.uuid, forKey: .uuid)
        try container.encode(self.url, forKey: .url)
        try container.encode(self.date, forKey: .date)
        try container.encode(ModelForgeInstant(self.instant), forKey: .instant)
        try container.encode(ModelForgeDuration(self.duration), forKey: .duration)
    }
}
