// Generated by ModelForge. Do not edit manually.

@file:OptIn(kotlin.time.ExperimentalTime::class, kotlin.uuid.ExperimentalUuidApi::class)
@file:UseSerializers(ModelForgeDecimalSerializer::class, ModelForgeDurationSerializer::class, ModelForgeInstantSerializer::class)

package com.example.models

import java.math.BigDecimal
import kotlin.time.Duration
import kotlin.time.Instant
import kotlin.uuid.Uuid
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

@Serializable
data class AllScalars(
    val s: String,
    val b: Boolean,
    val i32: Int,
    val i64: Long,
    val f: Float,
    val d: Double,
    val dec: BigDecimal,
    val uuid: Uuid,
    val url: String,
    val date: ModelForgeDate,
    val instant: Instant,
    val duration: Duration,
)
