// Generated by ModelForge. Do not edit manually.

@file:OptIn(kotlin.time.ExperimentalTime::class, kotlinx.serialization.ExperimentalSerializationApi::class)

package com.example.models

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonUnquotedLiteral
import kotlinx.serialization.json.jsonPrimitive
import java.math.BigDecimal
import kotlin.time.Duration
import kotlin.time.Instant

// Wire formats shared with the Swift models generated from the same schema:
//
//   Instant   ISO-8601 in UTC, as "YYYY-MM-DDThh:mm:ssZ"
//   Date      "yyyy-MM-dd"
//   Duration  ISO-8601 duration, such as PT1M30S
//   Decimal   a JSON number, not a string
//
// Supplying these here rather than relying on library serializers is what lets the
// generated code compile against kotlinx-serialization 1.8 and drop the
// kotlinx-datetime dependency entirely.

/// A calendar date with no time and no time zone.
///
/// Declared here rather than mapped to `kotlinx.datetime.LocalDate` so that models
/// generated from a schema carry no dependency the project did not already have.
@Serializable(with = ModelForgeDateSerializer::class)
data class ModelForgeDate(val year: Int, val month: Int, val day: Int) : Comparable<ModelForgeDate> {

    override fun toString(): String = "%04d-%02d-%02d".format(year, month, day)

    override fun compareTo(other: ModelForgeDate): Int =
        compareValuesBy(this, other, { it.year }, { it.month }, { it.day })
}

object ModelForgeDateSerializer : KSerializer<ModelForgeDate> {

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("ModelForgeDate", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: ModelForgeDate) {
        encoder.encodeString(value.toString())
    }

    override fun deserialize(decoder: Decoder): ModelForgeDate {
        val text = decoder.decodeString()
        val parts = text.split("-")
        require(parts.size == 3) { "Expected a date as yyyy-MM-dd, found $text." }
        return ModelForgeDate(parts[0].toInt(), parts[1].toInt(), parts[2].toInt())
    }
}

object ModelForgeInstantSerializer : KSerializer<Instant> {

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Instant) {
        encoder.encodeString(value.toString())
    }

    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}

object ModelForgeDurationSerializer : KSerializer<Duration> {

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Duration", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Duration) {
        encoder.encodeString(value.toIsoString())
    }

    override fun deserialize(decoder: Decoder): Duration = Duration.parse(decoder.decodeString())
}

/// Written as a JSON number so it matches Swift's `Decimal`, which encodes as one.
object ModelForgeDecimalSerializer : KSerializer<BigDecimal> {

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Decimal", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: BigDecimal) {
        if (encoder is JsonEncoder) {
            encoder.encodeJsonElement(JsonUnquotedLiteral(value.toPlainString()))
        } else {
            encoder.encodeString(value.toPlainString())
        }
    }

    override fun deserialize(decoder: Decoder): BigDecimal =
        if (decoder is JsonDecoder) {
            BigDecimal(decoder.decodeJsonElement().jsonPrimitive.content)
        } else {
            BigDecimal(decoder.decodeString())
        }
}