// Generated by ModelForge. Do not edit manually.

@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)

package com.example.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/** Something that happened to an account. */
@Serializable
@JsonClassDiscriminator("kind")
sealed interface UserAction

@Serializable
@SerialName("renamed")
data class RenameAction(
    /** The name the account now has. */
    val name: String,
) : UserAction

@Serializable
@SerialName("changedEmail")
data class ChangeEmailAction(
    val email: String?,
) : UserAction
