// Generated by ModelForge. Do not edit manually.

import Foundation

/// Something that happened to an account.
enum UserAction: Codable, Equatable, Sendable {
    case renamed(RenameAction)
    case changedEmail(ChangeEmailAction)

    private enum CodingKeys: String, CodingKey {
        case discriminator = "kind"
    }

    private enum Discriminator: String, Codable {
        case renamed
        case changedEmail
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(Discriminator.self, forKey: .discriminator) {
        case .renamed:
            self = .renamed(try RenameAction(from: decoder))
        case .changedEmail:
            self = .changedEmail(try ChangeEmailAction(from: decoder))
        }
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .renamed(let value):
            try container.encode(Discriminator.renamed, forKey: .discriminator)
            try value.encode(to: encoder)
        case .changedEmail(let value):
            try container.encode(Discriminator.changedEmail, forKey: .discriminator)
            try value.encode(to: encoder)
        }
    }
}

struct RenameAction: Identifiable, Codable, Equatable, Sendable {
    /// The name the account now has.
    let name: String

    var id: String { name }
}

struct ChangeEmailAction: Codable, Equatable, Sendable {
    let email: String?

    private enum CodingKeys: String, CodingKey {
        case email
    }

    init(email: String?) {
        self.email = email
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.email = try container.decode((String?).self, forKey: .email)
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.email, forKey: .email)
    }
}
