// Generated by ModelForge. Do not edit manually.

import Foundation

// Wire formats shared with the Kotlin models generated from the same schema:
//
//   Instant   ISO-8601 in UTC, as "YYYY-MM-DDThh:mm:ssZ"
//   Date      "yyyy-MM-dd"
//   Duration  ISO-8601 duration, such as PT1M30S
//
// Foundation's own Codable conformances do not produce any of these, which is why
// the generated models route these fields through the helpers below.

// MARK: - Date

/// A calendar date with no time and no time zone.
///
/// Foundation has no date-only type — `Date` is an instant — so the schema's
/// `Date` becomes this, and means the same thing here as it does in the Kotlin
/// models.
struct ModelForgeDate: Codable, Hashable, Sendable, Comparable, CustomStringConvertible {

    var year: Int
    var month: Int
    var day: Int

    init(year: Int, month: Int, day: Int) {
        self.year = year
        self.month = month
        self.day = day
    }

    var description: String {
        String(format: "%04d-%02d-%02d", year, month, day)
    }

    static func < (lhs: ModelForgeDate, rhs: ModelForgeDate) -> Bool {
        (lhs.year, lhs.month, lhs.day) < (rhs.year, rhs.month, rhs.day)
    }

    init(from decoder: any Decoder) throws {
        let text = try decoder.singleValueContainer().decode(String.self)
        let parts = text.split(separator: "-", maxSplits: 3, omittingEmptySubsequences: false)
        guard parts.count == 3,
              let year = Int(parts[0]), let month = Int(parts[1]), let day = Int(parts[2]),
              (1...12).contains(month), (1...31).contains(day) else {
            throw DecodingError.dataCorrupted(.init(
                codingPath: decoder.codingPath,
                debugDescription: "Expected a date as yyyy-MM-dd, found \(text)."))
        }
        self.init(year: year, month: month, day: day)
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(description)
    }
}

// MARK: - Instant

/// Codes a `Date` as an ISO-8601 instant in UTC.
///
/// Fractional seconds are written only when there are any, which is what the
/// Kotlin side does too, so identical values usually produce identical text.
struct ModelForgeInstant: Codable, Hashable, Sendable {

    var value: Date

    init(_ value: Date) { self.value = value }

    // Format styles rather than `ISO8601DateFormatter`: the formatter is a
    // non-`Sendable` class, so holding one in a `static let` is an error under the
    // Swift 6 language mode — which is the mode the code this lands in is likely to
    // be built in. These are value types and carry no such problem.
    private static let withFraction = Date.ISO8601FormatStyle(includingFractionalSeconds: true)
    private static let withoutFraction = Date.ISO8601FormatStyle()

    init(from decoder: any Decoder) throws {
        let text = try decoder.singleValueContainer().decode(String.self)
        guard let date = (try? Self.withFraction.parse(text))
                ?? (try? Self.withoutFraction.parse(text)) else {
            throw DecodingError.dataCorrupted(.init(
                codingPath: decoder.codingPath,
                debugDescription: "Expected an ISO-8601 instant, found \(text)."))
        }
        self.value = date
    }

    func encode(to encoder: any Encoder) throws {
        let seconds = value.timeIntervalSince1970
        let text = seconds == seconds.rounded()
            ? Self.withoutFraction.format(value)
            : Self.withFraction.format(value)
        var container = encoder.singleValueContainer()
        try container.encode(text)
    }
}

// MARK: - Duration

/// Codes a `Duration` as an ISO-8601 duration.
///
/// Swift's own conformance writes a two-element array of internal components,
/// which nothing on the other platform can read.
struct ModelForgeDuration: Codable, Hashable, Sendable {

    var value: Duration

    init(_ value: Duration) { self.value = value }

    init(from decoder: any Decoder) throws {
        let text = try decoder.singleValueContainer().decode(String.self)
        guard let duration = Self.parse(text) else {
            throw DecodingError.dataCorrupted(.init(
                codingPath: decoder.codingPath,
                debugDescription: "Expected an ISO-8601 duration, found \(text)."))
        }
        self.value = duration
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(Self.format(value))
    }

    /// `PT1M30S`, `PT0.5S`, `P1DT2H`, `PT0S`.
    static func format(_ duration: Duration) -> String {
        let components = duration.components
        var seconds = components.seconds
        let attoseconds = components.attoseconds
        let negative = seconds < 0 || attoseconds < 0
        if negative {
            seconds = -seconds
        }
        let fraction = abs(Double(attoseconds)) / 1e18

        let days = seconds / 86_400
        let hours = (seconds % 86_400) / 3_600
        let minutes = (seconds % 3_600) / 60
        let wholeSeconds = seconds % 60

        var text = negative ? "-P" : "P"
        if days != 0 { text += "\(days)D" }
        if hours != 0 || minutes != 0 || wholeSeconds != 0 || fraction != 0 || days == 0 {
            text += "T"
            if hours != 0 { text += "\(hours)H" }
            if minutes != 0 { text += "\(minutes)M" }
            if wholeSeconds != 0 || fraction != 0 || (hours == 0 && minutes == 0) {
                if fraction == 0 {
                    text += "\(wholeSeconds)S"
                } else {
                    let combined = Double(wholeSeconds) + fraction
                    text += String(format: "%gS", combined)
                }
            }
        }
        return text
    }

    static func parse(_ text: String) -> Duration? {
        var remainder = Substring(text)
        var sign = 1.0
        if remainder.hasPrefix("-") { sign = -1; remainder = remainder.dropFirst() }
        else if remainder.hasPrefix("+") { remainder = remainder.dropFirst() }
        guard remainder.hasPrefix("P") else { return nil }
        remainder = remainder.dropFirst()

        var total = 0.0
        var inTime = false
        var number = ""

        for character in remainder {
            if character == "T" {
                inTime = true
                continue
            }
            if character.isNumber || character == "." || character == "," {
                number.append(character == "," ? "." : character)
                continue
            }
            guard let magnitude = Double(number) else { return nil }
            number = ""
            switch (character, inTime) {
            case ("D", _): total += magnitude * 86_400
            case ("H", true): total += magnitude * 3_600
            case ("M", true): total += magnitude * 60
            case ("S", true): total += magnitude
            default: return nil
            }
        }
        guard number.isEmpty else { return nil }
        return .seconds(sign * total)
    }
}