// Generated by ModelForge. Do not edit manually.

@file:OptIn(kotlin.time.ExperimentalTime::class, kotlin.uuid.ExperimentalUuidApi::class, kotlinx.serialization.ExperimentalSerializationApi::class)
@file:UseSerializers(ModelForgeInstantSerializer::class)

package com.example.models

import kotlin.time.Instant
import kotlin.uuid.Uuid
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import kotlinx.serialization.UseSerializers

/** A user account in the application. */
@Serializable
data class User(
    /** Stable account identifier. */
    @SerialName("user_id")
    val id: UserID,
    val name: String,
    val email: String?,
    @EncodeDefault
    val status: UserStatus = UserStatus.ACTIVE,
    @EncodeDefault
    val retries: Int = 0,
    @EncodeDefault
    val ratio: Double = 2.0,
    @EncodeDefault
    val tags: List<String> = emptyList(),
    @EncodeDefault
    val metadata: Map<String, String> = emptyMap(),
    val createdAt: Instant,
    @Transient
    val isSelected: Boolean = false,
)

/** How far along an account is. */
@Serializable
enum class UserStatus {
    @SerialName("active")
    ACTIVE,
    @SerialName("suspended")
    SUSPENDED,
    @SerialName("gone")
    DELETED,
}

typealias UserID = Uuid
