// Generated by ModelForge. Do not edit manually.

import Foundation

/// A user account in the application.
struct User: Codable, Equatable, Sendable {
    /// Stable account identifier.
    let id: UserID
    let name: String
    let email: String?
    let status: UserStatus
    let retries: Int32
    let ratio: Double
    let tags: [String]
    let metadata: [String: String]
    let createdAt: Date
    let isSelected: Bool

    private enum CodingKeys: String, CodingKey {
        case id = "user_id"
        case name
        case email
        case status
        case retries
        case ratio
        case tags
        case metadata
        case createdAt
    }

    init(
        id: UserID,
        name: String,
        email: String?,
        status: UserStatus = .active,
        retries: Int32 = 0,
        ratio: Double = 2,
        tags: [String] = [],
        metadata: [String: String] = [:],
        createdAt: Date,
        isSelected: Bool = false
    ) {
        self.id = id
        self.name = name
        self.email = email
        self.status = status
        self.retries = retries
        self.ratio = ratio
        self.tags = tags
        self.metadata = metadata
        self.createdAt = createdAt
        self.isSelected = isSelected
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UserID.self, forKey: .id)
        self.name = try container.decode(String.self, forKey: .name)
        self.email = try container.decode((String?).self, forKey: .email)
        self.status = try container.decodeIfPresent(UserStatus.self, forKey: .status) ?? .active
        self.retries = try container.decodeIfPresent(Int32.self, forKey: .retries) ?? 0
        self.ratio = try container.decodeIfPresent(Double.self, forKey: .ratio) ?? 2
        self.tags = try container.decodeIfPresent([String].self, forKey: .tags) ?? []
        self.metadata = try container.decodeIfPresent([String: String].self, forKey: .metadata) ?? [:]
        let createdAt = try container.decode(ModelForgeInstant.self, forKey: .createdAt)
        self.createdAt = createdAt.value
        self.isSelected = false
    }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.email, forKey: .email)
        try container.encode(self.status, forKey: .status)
        try container.encode(self.retries, forKey: .retries)
        try container.encode(self.ratio, forKey: .ratio)
        try container.encode(self.tags, forKey: .tags)
        try container.encode(self.metadata, forKey: .metadata)
        try container.encode(ModelForgeInstant(self.createdAt), forKey: .createdAt)
    }
}

/// How far along an account is.
enum UserStatus: String, Codable, Sendable {
    case active
    case suspended
    case deleted = "gone"
}

typealias UserID = UUID
